//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailRoadVPN.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RailRoadVPN.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connect problem.
        /// </summary>
        internal static string check_internet_connect_header {
            get {
                return ResourceManager.GetString("check_internet_connect_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems there is no internet connection. Please check it..
        /// </summary>
        internal static string check_internet_connect_message {
            get {
                return ResourceManager.GetString("check_internet_connect_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect VPN first.
        /// </summary>
        internal static string disconnect_vpn_first {
            get {
                return ResourceManager.GetString("disconnect_vpn_first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupt disconnecting.
        /// </summary>
        internal static string disconnect_while_connect_header {
            get {
                return ResourceManager.GetString("disconnect_while_connect_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to interrupt connecting to VPN, press Semaphore button again.
        /// </summary>
        internal static string disconnect_while_connect_message {
            get {
                return ResourceManager.GetString("disconnect_while_connect_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter PIN-CODE.
        /// </summary>
        internal static string enter_pin_label {
            get {
                return ResourceManager.GetString("enter_pin_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET PIN-CODE.
        /// </summary>
        internal static string get_pincode_text_link {
            get {
                return ResourceManager.GetString("get_pincode_text_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click.
        /// </summary>
        internal static string help_1_text_label {
            get {
                return ResourceManager.GetString("help_1_text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semaphore to disconnect VPN.
        /// </summary>
        internal static string help_2_green_text_label {
            get {
                return ResourceManager.GetString("help_2_green_text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to semaphore to connect VPN.
        /// </summary>
        internal static string help_2_text_label {
            get {
                return ResourceManager.GetString("help_2_text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your submit. We will answer you by email as soon as possible. Your ticket number:.
        /// </summary>
        internal static string help_form_anonym_thank_message {
            get {
                return ResourceManager.GetString("help_form_anonym_thank_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill required fields.
        /// </summary>
        internal static string help_form_bad_data_header {
            get {
                return ResourceManager.GetString("help_form_bad_data_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string help_form_cancel_btn {
            get {
                return ResourceManager.GetString("help_form_cancel_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe your problem.
        /// </summary>
        internal static string help_form_description_label {
            get {
                return ResourceManager.GetString("help_form_description_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string help_form_email_label {
            get {
                return ResourceManager.GetString("help_form_email_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter problem description to help us to resolve it as soon as possible.
        /// </summary>
        internal static string help_form_empty_description_message {
            get {
                return ResourceManager.GetString("help_form_empty_description_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email, we will send an email updating information about your problem.
        /// </summary>
        internal static string help_form_empty_email_message {
            get {
                return ResourceManager.GetString("help_form_empty_email_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why don&apos;t want send us log files?.
        /// </summary>
        internal static string help_form_logfilescheckbox_notchecked_header {
            get {
                return ResourceManager.GetString("help_form_logfilescheckbox_notchecked_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log files will help us very strong and we can be sure to hlep you as soon as possible. Log file it is file with events during application RailRoadVPN work process and no information about your personal data. Are you sure you don&apos;t want send us log file and improve time of solving your problem? If you have change your mind - press No and check checkbox on help form..
        /// </summary>
        internal static string help_form_logfilescheckbox_notchecked_message {
            get {
                return ResourceManager.GetString("help_form_logfilescheckbox_notchecked_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string help_form_send_btn {
            get {
                return ResourceManager.GetString("help_form_send_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your submit. We will answer you by email as soon as possible. Also you can follow your ticket status in your profile on site: https://rroadvpn.net/. Your ticket number:.
        /// </summary>
        internal static string help_form_thank_message {
            get {
                return ResourceManager.GetString("help_form_thank_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to green.
        /// </summary>
        internal static string help_green_text_label {
            get {
                return ResourceManager.GetString("help_green_text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to red.
        /// </summary>
        internal static string help_red_text_label {
            get {
                return ResourceManager.GetString("help_red_text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to get pincode?\r\n1. Press GET PIN-CODE link \r\n2. Your browser will open site\r\n3. Sign in or sign up\r\n4. Press GENERATE PIN-CODE button.
        /// </summary>
        internal static string how_get_pin_text_label {
            get {
                return ResourceManager.GetString("how_get_pin_text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t connect to VPN.
        /// </summary>
        internal static string main_form_tap_adapter_busy_header {
            get {
                return ResourceManager.GetString("main_form_tap_adapter_busy_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems you are connected to VPN. Disconnect first, than press Connect Semaphore again..
        /// </summary>
        internal static string main_form_tap_adapter_busy_message {
            get {
                return ResourceManager.GetString("main_form_tap_adapter_busy_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For propery work VPN you have to install driver. Please relaunch application and try again..
        /// </summary>
        internal static string main_form_tap_adapter_not_installed_message {
            get {
                return ResourceManager.GetString("main_form_tap_adapter_not_installed_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string menu_item_logout {
            get {
                return ResourceManager.GetString("menu_item_logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Help?.
        /// </summary>
        internal static string menu_item_need_help {
            get {
                return ResourceManager.GetString("menu_item_need_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string menu_item_profile {
            get {
                return ResourceManager.GetString("menu_item_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string menu_logout_text_label {
            get {
                return ResourceManager.GetString("menu_logout_text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string menu_myprofile_text_label {
            get {
                return ResourceManager.GetString("menu_myprofile_text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Help?.
        /// </summary>
        internal static string menu_needhelp_text_label {
            get {
                return ResourceManager.GetString("menu_needhelp_text_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update required.
        /// </summary>
        internal static string new_version_header {
            get {
                return ResourceManager.GetString("new_version_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version of application. You have to download new version to continue. Open downloads page in your browser?.
        /// </summary>
        internal static string new_version_message {
            get {
                return ResourceManager.GetString("new_version_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown system error.
        /// </summary>
        internal static string unknown_system_error_header {
            get {
                return ResourceManager.GetString("unknown_system_error_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection - if problem still exist - please try again later or use feedback form from menu, or wirte us about your problem by email: support@rroadvpn.net.
        /// </summary>
        internal static string unknown_system_error_message {
            get {
                return ResourceManager.GetString("unknown_system_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VPN STATUS.
        /// </summary>
        internal static string vpn_connect_status {
            get {
                return ResourceManager.GetString("vpn_connect_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong pincode.
        /// </summary>
        internal static string wrong_pin_error_header {
            get {
                return ResourceManager.GetString("wrong_pin_error_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered wrong pincode, please check it or generate new one at profile page.
        /// </summary>
        internal static string wrong_pin_error_message {
            get {
                return ResourceManager.GetString("wrong_pin_error_message", resourceCulture);
            }
        }
    }
}
