//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RailRoadVPN.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RailRoadVPN.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interrupt disconnecting.
        /// </summary>
        internal static string disconnect_while_connect_header {
            get {
                return ResourceManager.GetString("disconnect_while_connect_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to interrupt connecting to VPN, press Semaphore button again.
        /// </summary>
        internal static string disconnect_while_connect_message {
            get {
                return ResourceManager.GetString("disconnect_while_connect_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong pincode.
        /// </summary>
        internal static string wrong_pin_error_header {
            get {
                return ResourceManager.GetString("wrong_pin_error_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered wrong pincode, please check it or generate new one at profile page.
        /// </summary>
        internal static string wrong_pin_error_message {
            get {
                return ResourceManager.GetString("wrong_pin_error_message", resourceCulture);
            }
        }
    }
}
